version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - API_KEY=$API_KEY_CLOUDFLARE
      - ZONE=$ZONE
      - PROXIED=true
      - PUID=$PUID
      - PGID=$PGID