---
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=$SERVERURL
      - SERVERPORT=$SERVERPORT
      - PEERS=4
      - PEERDNS=$PEERDNS
      - INTERNAL_SUBNET=$INTERNAL_SUBNET
    volumes:
      - /wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:$SERVERPORT/udp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped